spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test

management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - heath
          - loggers
          - shutdown
          - threaddump
          - info