spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobapp
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop