spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test

# Actuator
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

info:
  app-name: "MyApp"
  app-description: "MyDescription"